[tool.pysen]
version = "0.10"

[tool.pysen.lint]
enable_black = true
enable_flake8 = true
enable_isort = true
enable_mypy = true
mypy_preset = "strict"
py_version = "py36"
isort_known_first_party = ["rosidl_generator_mypy"]
[tool.pysen.lint.source]
  includes = [".", "bin/rosidl_generator_mypy"]
  excludes = [".tox", "venv"]
[[tool.pysen.lint.mypy_targets]]
  paths = ["."]
